### PR TITLE
Add client income attribute

### PR DESCRIPTION
**Pull request by jovitaanderson**
- Implement client to have income as an attribute when adding and editing a client info. 
- When adding a client, income attribute is **required**, prefix used to add income attribute is `i/`.
- Did manual testing

<ins> Additional changes made: </ins>
- Update existing test codes to include income attribute to `Person`, tested and passed*
- Update all JavaDoc and comments containing address book to financial book

*Existing data in `/data/addressbook.json` must be deleted and run the app again for the new sample data, as the old data is not recognized due to the new required formatting of the income prefix `i/`.

### CODE REVIEW

**Comment by leecaregene** [comment]
You can click on **details** of **Java CI / build (ubuntu-latest)** to see what checks went wrong.

**Comment by jovitaanderson** [comment]
Thanks! @leecaregene

**Comment by leecaregene** [comment]
Looks good to merge, however in my opinion it would be better to change `financial book` in the comments to `FinBook` instead to reduce confusion.

**Comment by jovitaanderson** [comment]
> Looks good to merge, however in my opinion it would be better to change `financial book` in the comments to `FinBook` instead to reduce confusion.

Good point! I have made the necessary changes

**Comment by shaniceng** [comment]
LGTM!

**Pull request merged**
